config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'dashboard/home'
  get 'dashboard/catalog'
  get 'dashboard/configuration'
  get 'dashboard/info'
  get 'dashboard/notices'
  get 'dashboard/weather'
  get 'dashboard/profile'
  get 'dashboard/help'
  get 'dashboard/news'
  get 'site/home', :path => "/"

  get 'site/how', :path => "/how-it-works"

  get 'site/terms', :path => "/terms-conditions"

  get 'site/team', :path => "/team"

  devise_for :users, path: '/', path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'password', 
    confirmation: 'confirmation', 
    unlock: 'unlock', 
    registration: 'register', 
    sign_up: 'new' 
  }

  root 'site#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :notice
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         # :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Devise doing his job
  before_action :authenticate_user!
  layout :layout_by_resource

  add_breadcrumb "Inicio", "/"

  def after_sign_in_path_for(resource)
    :dashboard_home
  end  

  private
	  def layout_by_resource
	  	return "public" if devise_controller?
	  	"application"
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        @comment = Comment.new
        format.html { redirect_to :back, notice: 'Se ha comentado correctamente' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user, :date, :body, :image, :notice_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def home
  	add_breadcrumb "Dashboard", dashboard_home_path
  end

  def catalog
  	add_breadcrumb "Dashboard", dashboard_home_path
  	add_breadcrumb "Catálogo"
  end
  
  def configuration
  	add_breadcrumb "Dashboard", dashboard_home_path
  	add_breadcrumb "Configuración"
    @notices = Notice.all
    num = 1
    @notices.each do |notice|
      notice.user = "Usuario "+ num.to_s
      notice.save
      num+=1
    end 
  end
  
  def info
  	add_breadcrumb "Dashboard", dashboard_home_path
  	add_breadcrumb "Información"
  end
  
  def notices
  	add_breadcrumb "Dashboard", dashboard_home_path
  	add_breadcrumb "Social"
    @notices = Notice.all
    @comment = Comment.new
  end
  
  def weather
  	add_breadcrumb "Dashboard", dashboard_home_path
  	add_breadcrumb "Clima"
  end

  def news
    add_breadcrumb "Dashboard", dashboard_home_path
    add_breadcrumb "Noticias"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!, except: [:home, :how, :terms, :team]
  layout "public"

  def home
  	redirect_to dashboard_home_path if current_user
  	@resource = User.new
  end

  def how
  end

  def terms
  end

  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" hidden>
    <%= f.label :user %><br>
    <%= f.text_field :user, value: @notice.user %>
  </div>
  <div class="field" hidden>
    <%= f.label :date %><br>
    <%= f.datetime_select :date, value: Time.now %>
  </div>
  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="field" hidden>
    <%= f.label :image %><br>
    <%= f.text_field :image, value: "1.png" %>
  </div>
  <div class="field" hidden>
    <%= f.label :notice_id %><br>
    <%= f.text_field :notice_id, value: @notice.id %>
  </div>
  <div class="actions">
    <%= f.submit "Comentar", class: "btn blue btn-flat" %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<p class="grey-text"><%= image_tag("users/"+@commentt.image, alt: 'image-comment', class: 'comment-image ')%>
 <%= @commentt.user %>  a las <%= l(  @commentt.date , format: '%H:%M:%S de %d-%m-%Y') %></p>
<b>
  <%= @commentt.body %>
  
</b>  
<hr>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Body</th>
      <th>Image</th>
      <th>Notice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.date %></td>
        <td><%= comment.body %></td>
        <td><%= comment.image %></td>
        <td><%= comment.notice %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/dashboard/catalog.html.erb
<div class="row">
	<div class="col m2 s1"></div>  
	<div class="col m8 s10 card"> 
		<br>
		<div class="card-title">Catálogo</div>
		<div class="card-body">
			<% prng = Random.new%>	
			
			<b>Tienda de pesca 1 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/1.jpeg", alt: 'image', class: 'catalog-image')%> <br>	
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 1 en catalogo.</p>	
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 2 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/2.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 2 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 3 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/3.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 3 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 4 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/4.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 4 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 5 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/5.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 5 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 6 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/6.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 6 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 7 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/7.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 7 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 8 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/8.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 8 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 9 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/9.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 9 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 10 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/10.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 10 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 11 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/11.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 11 en catalogo.</p>			
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

			<b>Tienda de pesca 12 </b>
			<p><%= Time.now %></p>
			<p>$ <%= prng.rand(300000) %></p>
			<div class="row">
				<div class="col m6 s6">
					<%= image_tag("product/12.jpeg", alt: 'image', class: 'catalog-image')%> <br>		
				</div>
				<div class="col m6 s6">
					<p>Descripción de producto 12 en catalogo.</p>	
				</div>
			</div>
			<div class="btn green">Ver detalle</div>						
			<hr>

		</div>
	</div>
	<br>
	<div class="col m2 s1"></div> 
</div>

app/views/dashboard/configuration.html.erb
<div class="row" style="margin-right: 20px;">
	<div class="col m1 s1"></div>
	<div class="col m5 s5 card"> 
		<br>
		<a href="#">Editar <i class="fa fa-pencil"></i></a>
		<div class="card-title grey-text" align="center">John Doe</div>
		<div class="card-body grey-text">
			<div class="userView" align="center">
			      <%= image_tag('logos/user.JPG', alt: 'Back PescApp', class: 'circle user-image')%>
			      <br>
			      <span class="grey-text email"><%= current_user.email %></span><br>
			      <%= image_tag('stars.png', alt: 'stars', class: '')%>
			      
			</div>
			<table class="table">
				<tr>
					<td>En PescApp desde:</td>
					<td><%= l(current_user.created_at, format: '%d-%m-%Y %H:%M:%S') %></td>
				</tr>
				<tr>
					<td>Lugar de pesca preferido</td>
					<td>Lago Colbún, Talca</td>
				</tr>
				<tr>
					<td>Ultima pesca:</td>
					<td>San Antonio</td>
				</tr>
				<tr>
					<td>Número de publicaciones</td>
					<td>290</td>
				</tr>
				
			</table>
		</div>
	</div>  
	<div class="col m1 s1"></div> 
	<div class="col m5 s5 card"> 
		<br>
		<div class="card-title">Configuración</div>
		<div class="card-body">
		<br>
		<!-- Switch -->
		  <div class="switch">
		  	Configuración 1: &nbsp;&nbsp;
		    <label>
		      Off
		      <input type="checkbox">
		      <span class="lever"></span>
		      On
		    </label>
		  </div>
			<br>
			<!-- Switch -->
		  <div class="switch">
		  	Configuración 2: &nbsp;&nbsp;
		    <label>
		      Off
		      <input type="checkbox">
		      <span class="lever"></span>
		      On
		    </label>
		  </div>
			<br>
			<!-- Switch -->
		  <div class="switch">
		  	Configuración 3: &nbsp;&nbsp;
		    <label>
		      Off
		      <input type="checkbox">
		      <span class="lever"></span>
		      On
		    </label>
		  </div>
			<br>
			<!-- Switch -->
		  <div class="switch">
		  	Configuración 4: &nbsp;&nbsp;
		    <label>
		      Off
		      <input type="checkbox">
		      <span class="lever"></span>
		      On
		    </label>
		  </div>
			<br>
			<!-- Switch -->
		  <div class="switch">
		  	Configuración 5: &nbsp;&nbsp;
		    <label>
		      Off
		      <input type="checkbox">
		      <span class="lever"></span>
		      On
		    </label>
		  </div>
			<br>
			<!-- Switch -->
		  <div class="switch">
		  	Configuración 6: &nbsp;&nbsp;
		    <label>
		      Off
		      <input type="checkbox">
		      <span class="lever"></span>
		      On
		    </label>
		  </div>
		  <br>
		</div>
	</div>

</div>

app/views/dashboard/info.html.erb
<div class="row">
	<div class="col m1 s1"></div>  
	<div class="col m10 s10 card"> 
		<br>
		<div class="card-title">Información</div>
			<p>En estos apartados podrás encontrar tutoriales y artículos para pescadores principiantes y avanzados que desean aprender a pescar o a reforzar sus conocimientos y técnicas de pesca.</p>
			<p><strong>Nudos</strong></p>
			<ul>
			<li><a title="El Primer Nudo de Pesca que Debes Aprender" href="#el-primer-nudo-de-pesca-que-debes-aprender/">El Primer Nudo de Pesca que Debes Aprender</a>
			<ul>
			<li>Nudos de Pesca
			<ul>
			<li><a title="Nudo Palomar de Pesca" href="#nudo-palomar-para-pesca/">Nudo Palomar</a></li>
			<li><a title="Nudo Clinch Mejorado" href="#nudo-clinch-mejorado/">Nudo Clinch</a></li>
			<li><a title="¿Cómo hacer el Nudo de Pesca Trilene?" href="#nudo-de-pesca-trilene/">Nudo Trilene</a></li>
			<li><a href="#nudo-rapala/">Nudo Rápala</a></li>
			<li><a href="#nudo-de-pesca-duncan/">Nudo Duncan</a></li>
			<li><a href="#nudo-snell-estandar/">Nudo Snell Estandar</a></li>
			</ul>
			</li>
			</ul>
			</li>
			<li><a title="10 Nudos de Pesca que Todo pescador debe Saber" href="#10-nudos-de-pesca-que-todo-pescador-debe-aprender/">10 Nudos Que Todo Pescador Debe Saber</a></li>
			<li><a href="#nudos-para-lineas-fluorocarbono/">Nudos para Atar Líneas de Fluorocarbono</a></li>
			</ul>
			<p><strong>Aparejos de Pesca</strong></p>
			<ul>
			<li><a title="Cómo Poner un Hilo al Carrete de Spinning | Video Tutoriales" href="#pesca-para-principiantes/como-poner-un-hilo-al-carrete-video-tutoriales/" target="_blank">Cómo Poner Hilo al Carrete</a></li>
			<li><a title="¿Cómo Atar una Línea a un Anzuelo?" href="#pesca-para-principiantes/como-atar-una-linea-a-un-anzuelo/" target="_blank">Cómo Atar el Hilo al Anzuelo</a></li>
			<li><a title="¿Cuando usar Quitavueltas para Pescar?" href="#cuando-usar-quitavueltas-de-pesca/">Cuando Usar Quitavueltas</a></li>
			<li><a title="Swivel (Sacavueltas) y Snaps, ¿para qué sirven?" href="#swivel-y-snaps-para-que-sirven/">Para qué Sirven los Quitavueltas Y Snaps (Broches)</a></li>
			</ul>
			<p><strong>Señuelos</strong></p>
			<ul>
			<li><a title="Señuelos de Hélice (Torpedos o Propellers)" href="#senuelos-de-helice-torpedos/">Técnicas de Pesca con Señuelos de Hélice (Torpedos o Propellers)</a></li>
			<li><a title="¿Cómo y cuando pescar con Popper Fish?" href="#como-y-cuando-pescar-con-popper-fish/">¿Cómo y cuándo pescar con Popper?</a></li>
			<li><a href="#jerkbaits/">¿Qué son los Jerkbaits?</a></li>
			<li><a href="#colores-de-senuelos-que-esto-no-lo-sabias/">Los Peces Ven Colores ¿Qué colores de señuelos utilizar?</a></li>
			</ul>
			<p><strong>Caña de Pescar</strong></p>
			<ul>
			<li><a title="Cómo lanzar y agarrar una caña de Pescar de Spinning" href="#como-lanzar-y-agarrar-una-cana-de-pescar-de-spinning/">Cómo Agarrar y Lanzar una Caña de Spinning Correctamente</a></li>
			<li><a href="#escoger-una-cana-de-pescar-guia-para-principiantes/">¿Cómo Elegir unar una Caña de Pescar? &#8211; Guía de Compra para Principiantes</a></li>
			<li><a href="#canas-de-pescar-para-ninos-como-elegir-la-correcta/">Cañas de Pescar para Niños &#8211; ¿Cómo Elegir la Correcta?</a></li>
			</ul>
			<p><strong>Carretes de Pesca</strong></p>
			<ul>
			<li><a title="Guía para Elegir el Reel de Pesca Adecuado" href="#reel-de-pesca-adecuado-para-pesca-de-bass-tomando-la-decision-correcta/">Guía para Elegir un Carrete</a></li>
			<li><a title="Especificaciones de un Carrete de Pesca, No te Intimides" href="#especificaciones-de-un-carrete-de-pesca-te-intimides/">Especificaciones de un Carrete de Pesca</a></li>
			<li><a href="#como-saber-si-un-carrete-de-pesca-es-bueno/">¿Cómo Saber si un Carrete de Pesca es Bueno?</a></li>
			</ul>
			<p><strong>Uso de Accesorios de Pesca</strong></p>
			<ul>
			<li><a href="#lentes-para-pescar-2014/">Lentes para Pescar &#8211; Lo que Debes Saber</a></li>
			<li><a href="#lentes-para-pescar-en-dias-nublados-u-oscuros/">Lentes para Pescar en Días Nublados o Lluviosos</a></li>
			</ul>
			<p><strong>Manual de Pesca</strong></p>
			<ul>
			<li><a href="#manual-pesca-principiantes/">Manual de Pesca para Pescadores (Guía del Pescador de Fin de Semana)</a></li>
			</ul>

		<div class="card-body">
		</div>
	</div>
	<br>
	<div class="col m1 s1"></div> 
</div>

app/views/dashboard/notices.html.erb
<div class="row">
	<div class="col m1 s1"></div>  
	<div class="col m10 s10 card"> 
		<br>
		<div class="card-title" align="center">Social</div>
		
			<% @notices.each do |notice|
				@notice = notice
				%>
				<div class="card"> 
					<br>
					<h6 class="grey-text"><%= notice.user %> a las <%= l( notice.date , format: '%H:%M:%S de %d-%m-%Y') %></h6>
					<div class="card-content">
						<div class="row">
							<div class="col s6 m6">
								 <%= image_tag("notices/"+notice.image, alt: 'image', class: 'notice-image ')%>
							</div>
							<div class="col s6 m6">
								<%= notice.body %>
							</div>
						</div>
					</div>
					<% notice.comments.each do |commentt|
						@commentt = commentt%>
						<%= render 'comments/show', locals: { commentt: @commentt}%>
					<%end%>

					<%= render 'comments/form', locals: { notice: @notice}%>
				</div>	
			<%end%>
			<br>
		
	</div>
	<br>
	<div class="col m1 s1"></div> 
</div>

app/views/dashboard/profile.html.erb
<div class="row">
	<div class="col m4 s1"></div>  
	<div class="col m4 s10 card"> 
		<br>
		<div class="card-title grey-text" align="center">John Doe</div>
		<div class="card-body">
			<div class="userView" align="center">
			      <%= image_tag('logos/user.JPG', alt: 'Back PescApp', class: 'circle user-image')%>
			      <br>
			      <span class="grey-text email"><%= current_user.email %></span><br>
			      <%= image_tag('stars.png', alt: 'stars', class: '')%>
			      
			</div>
			<table class="table">
				<tr>
					<td>En PescApp desde:</td>
					<td><%= l(current_user.created_at, format: '%d-%m-%Y %H:%M:%S') %></td>
				</tr>
				<tr>
					<td>Lugar de pesca preferido</td>
					<td>Lago Colbún, Talca</td>
				</tr>
				<tr>
					<td>Ultima pesca:</td>
					<td>San Antonio</td>
				</tr>
				<tr>
					<td>Número de publicaciones</td>
					<td>290</td>
				</tr>
				
			</table>
		</div>
	</div>
	<br>
	<div class="col m4 s1"></div> 
</div>

app/views/dashboard/weather.html.erb
<div class="row">
	<div class="col m4 s1"></div>  
	<div class="col m4 s10 card"> 
		<br>
		<div class="card-title" align="center">Clima</div>
		<div class="card-body" align="center">
		<% 
			prng = Random.new
			number = prng.rand(30)
			if number > 15
				text = "Soleado"
				icon= "sun-o yellow-text"
			else
				text = "Nublado"
				icon= "cloud blue-text"
			end
		%>
		<p class="grey-text">
			<%= number %> °
		</p>
		<i class="fa fa-<%= icon %> fa-5x"></i>
		<br>
		<b><%= text %></b>
		</div>
	</div>
	<br>
	<div class="col m4 s1"></div> 
</div>

app/views/site/home.html.erb
<div class="container">
	
	<div class="row">
		<div class="col m8">
			<br>
			<div class="card">
				<div class="card-title" align="center">
					<span>Bienvenido a PescApp</span>
				</div>
				<div class="card-content">
					<div style="height:400px;background:#ddd;color:white;text-align:center;line-height:400px;"><%= image_tag('home-back.jpg', alt: 'Home', class: 'home')%></div>
					<hr>
					<p> Nuestro país ofrece enormes ventajas para el desarrollo de la pesca recreativa, 
					fundamentalmente por la diversidad de sus ecosistemas y bellezas naturales.
					Es por ello que ofrecemos nuestro servicio mediante la aplicación PescApp,
					la cual busca ser un apoyo para la realización de la pesca recreativa en 
					distintos lugares, ofreciendo a los usuarios diversas herramientas que
					ayuden a este proceso.

					Se entenderá por pesca recreativa la actividad pesquera realizada por 
					personas naturales que tiene por objeto la captura de especies hidrobiológicas 
					con aparejos de pesca de uso personal, sin fines de lucro para el pescador 
					y con propósito de deporte, turismo o entretención.</p>
				</div>
			</div>

		</div>
		<div class="col m4">
			<br>
			<div class="card">
				<div class="card-title" align="center">
					<span>Iniciar sesión</span>
				</div>
				<div class="card-content">
					
					<%= form_for(@resource, as: :user, url: session_path(:user)) do |f| %>
            <div class="form-group">
              <%= f.label "Correo electrónico" %>
              <%= f.email_field :email, autofocus: true, :placeholder => "name@example.colm", :class => "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "Contraseña" %><br />
              <%= f.password_field :password, autofocus: true, :placeholder => "********", :class => "form-control" %>
            </div>
          
            <div class="actions">
              <%= f.submit "Iniciar sesión", :class => "btn btn-primary float-right" %>
            </div>
          <% end %>

				</div>
			</div>

			<div class="card">
				<div class="card-content">

					<ul>
						<li><%= link_to "Registrarse", new_registration_path(:user) %></li>
            			<li><%= link_to "¿Olvidé mi contraseña?", new_password_path(:user) %></li>  
					</ul>
					
				</div>
			</div>
		</div>
	</div>
</div>

app/views/site/terms.html.erb
<div class="container">
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="panel-title"> Soporte </div>
		</div>
		<div class="panel-body">
			<h3> Soporte de PescApp</h3>
			<p> Por favor, contacta con soporte@pescapp.cl. </p>
			<hr>
			<h4> Contactar a PescApp </h4>
			<p> Por favor, contacta con nuestro soporte técnico </p>
			<h4> Preguntas Frecuentes </h4>
			<p> </p>
			<h4> Términos y condiciones </h4>
			<p> </p>
			<h4> Política de privacidad</h4>
			<p> </p>
		</div>
	</div>
</div>